#ifndef FTS_DEFINE_HPP
#define FTS_DEFINE_HPP

#define FTS_TIMEOUT_SEC (60)
#define FTS_RETRY_INTERVAL_USEC (2000000)

#define FTS_DEFAULT_MAX_CONCURRENT_QUERIES 128
#define FTS_DEFAULT_MAX_RESULTS 128
#define FTS_DEFAULT_MAX_RESULT_LIFETIME_SEC 50000


#endif /* FTS_DEFINE_HPP */
